# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- script: sqlpackage.exe /version
  workingDirectory: C:\Program Files\Microsoft SQL Server\160\DAC\bin\
  displayName: 'get sqlpackage version'

- script: az version
  displayName: 'get azure cli version'

- script: az login --service-principal -u $(sp-devops-principal-id) -p $(sp-devops-secret-value) --tenant 41b08d65-56af-477e-aa6b-9dc5cfc30723
  displayName: 'az login test'
